name: Update Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-deps:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install cargo-outdated
      run: cargo install cargo-outdated
      
    - name: Check for outdated dependencies
      run: cargo outdated
      
    - name: Update dependencies
      run: |
        cargo update
        cargo outdated -R || true
        
    - name: Check if there are changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "no_changes=true" >> $GITHUB_OUTPUT
        else
          echo "no_changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Pull Request
      if: steps.changes.outputs.no_changes == 'false'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "🤖 Auto-update dependencies"
        body: |
          This PR was automatically created to update dependencies.
          
          ## Changes
          - Updated Rust dependencies to latest compatible versions
          - Generated by GitHub Actions
          
          ## Testing
          - [ ] All tests pass
          - [ ] No breaking changes
          
        branch: auto-update-deps
        delete-branch: true
        labels: |
          dependencies
          automated 